tap "getantibody/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/command-not-found"
tap "homebrew/core"
tap "neovim/neovim"
brew "autojump", args: ["HEAD"]
brew "binutils", link: true
brew "coreutils"
brew "cscope"
brew "ctags"
brew "fd"
brew "findutils", args: ["with-default-names"]
brew "fzf"
brew "git"
brew "git-flow"
brew "grep", args: ["with-default-names"]
brew "htop"
brew "minicom"
brew "neovim"
brew "nmap"
brew "pandoc"
brew "python"
brew "reattach-to-user-namespace"
brew "ripgrep"
brew "ruby"
brew "ssh-copy-id"
brew "thefuck"
brew "tmux"
brew "tree"
brew "vim"
brew "wget"
brew "zsh"
brew "getantibody/tap/antibody"
cask "alfred"
cask "forklift"
cask "google-chrome"
cask "hex-fiend"
cask "iterm2"
cask "keka"
cask "qlstephen"
cask "suspicious-package"
